import { sqliteTable, text, integer, real, unique } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';
import { workspaces, courseComponents } from '../workspace/model';

// Local attendance tracks specific occurrences generated by CalendarService
export const attendance = sqliteTable('attendance', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  componentId: integer('component_id').notNull().references(() => courseComponents.id, { onDelete: 'cascade' }),
  occurrenceId: text('occurrence_id').notNull(), // Links to CalendarService effective occurrence ID
  identityStatus: text('identity_status', { enum: ['resolved', 'unresolved_legacy'] }).default('unresolved_legacy').notNull(),
  date: text('date').notNull(), // Specific date of the lecture
  source: text('source').default('local'), // Explicitly marking source
  status: text('status', { enum: ['present', 'absent', 'exempt', 'holiday', 'cancelled'] }).notNull(),
  markedAt: text('marked_at').default(sql`(CURRENT_TIMESTAMP)`),
  notes: text('notes'),
}, (table) => {
  return {
    occurrenceUnique: unique('occurrence_idx').on(table.occurrenceId)
  };
});

// Portal attendance is an aggregate snapshot, usually at the Course level, but optionally at Component level
export const portalAttendance = sqliteTable('portal_attendance', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  workspaceId: integer('workspace_id').notNull().references(() => workspaces.id, { onDelete: 'cascade' }),
  componentId: integer('component_id').references(() => courseComponents.id, { onDelete: 'cascade' }), // Nullable, only if portal provides component breakdown
  portalTotal: integer('portal_total'),
  portalPresent: integer('portal_present'),
  portalPercent: real('portal_percent'),
  checkedDate: text('checked_date').notNull(),
  screenshotUri: text('screenshot_uri'),
});
